<?php

use App\Http\Controllers\Api\EntityController;
use App\Http\Controllers\Api\PaymentWebhookController;
use App\Http\Controllers\Api\PublicWeddingController;
use App\Http\Controllers\Api\TenantAccessController;
use App\Http\Controllers\Api\TenantBadgeController;
use App\Http\Controllers\Api\TenantBillingController;
use App\Http\Controllers\Api\TenantBudgetController;
use App\Http\Controllers\Api\TenantCateringController;
use App\Http\Controllers\Api\TenantCommunicationController;
use App\Http\Controllers\Api\TenantDocumentController;
use App\Http\Controllers\Api\TenantEventController;
use App\Http\Controllers\Api\TenantGuestController;
use App\Http\Controllers\Api\TenantInventoryController;
use App\Http\Controllers\Api\TenantInvitationController;
use App\Http\Controllers\Api\TenantMediaController;
use App\Http\Controllers\Api\TenantOrganizationController;
use App\Http\Controllers\Api\TenantScheduleController;
use App\Http\Controllers\Api\TenantSeatingController;
use App\Http\Controllers\Api\TenantTeamController;
use App\Http\Controllers\Api\TenantTicketingController;
use App\Http\Controllers\Api\TenantVendorController;
use App\Http\Controllers\Api\UploadController;
use Illuminate\Support\Facades\Route;

Route::prefix('public')->group(function () {
    Route::post('/payments/webhooks/{provider}', PaymentWebhookController::class);
    Route::get('/invitations/{token}', [PublicWeddingController::class, 'invitation']);
    Route::put('/invitations/{token}', [PublicWeddingController::class, 'respond']);
    Route::post('/invitations/{token}/orders', [PublicWeddingController::class, 'invitationOrder']);
    Route::get('/table-menus/{table}', [PublicWeddingController::class, 'tableMenu']);
    Route::post('/table-menus/{table}/orders', [PublicWeddingController::class, 'tableOrder']);
});

Route::middleware(['web', 'auth'])->group(function () {
    Route::get('/organizations', [TenantOrganizationController::class, 'index']);
    Route::scopeBindings()->prefix('/organizations/{organization:slug}')->middleware('tenant')->group(function () {
        Route::get('/events', [TenantEventController::class, 'index']);
        Route::get('/events/{event:slug}', [TenantEventController::class, 'show']);
        Route::get('/events/{event:slug}/guests', [TenantGuestController::class, 'index']);
        Route::post('/events/{event:slug}/guests', [TenantGuestController::class, 'store']);
        Route::get('/events/{event:slug}/guests/{guest}', [TenantGuestController::class, 'show']);
        Route::put('/events/{event:slug}/guests/{guest}', [TenantGuestController::class, 'update']);
        Route::delete('/events/{event:slug}/guests/{guest}', [TenantGuestController::class, 'destroy']);
        Route::get('/events/{event:slug}/invitation', [TenantInvitationController::class, 'show']);
        Route::put('/events/{event:slug}/invitation', [TenantInvitationController::class, 'update']);
        Route::get('/events/{event:slug}/seating', [TenantSeatingController::class, 'index']);
        Route::post('/events/{event:slug}/seating/tables', [TenantSeatingController::class, 'store']);
        Route::put('/events/{event:slug}/seating/tables/{table}', [TenantSeatingController::class, 'update']);
        Route::delete('/events/{event:slug}/seating/tables/{table}', [TenantSeatingController::class, 'destroy']);
        Route::put('/events/{event:slug}/seating/layout', [TenantSeatingController::class, 'saveLayout']);
        Route::put('/events/{event:slug}/seating/assignments/{guest}', [TenantSeatingController::class, 'assign']);
        Route::get('/events/{event:slug}/schedule', [TenantScheduleController::class, 'index']);
        Route::post('/events/{event:slug}/schedule/items', [TenantScheduleController::class, 'store']);
        Route::put('/events/{event:slug}/schedule/items/{scheduleItem}', [TenantScheduleController::class, 'update']);
        Route::delete('/events/{event:slug}/schedule/items/{scheduleItem}', [TenantScheduleController::class, 'destroy']);
        Route::get('/events/{event:slug}/communications', [TenantCommunicationController::class, 'index']);
        Route::post('/events/{event:slug}/communications', [TenantCommunicationController::class, 'store']);
        Route::put('/events/{event:slug}/communications/read-all', [TenantCommunicationController::class, 'markAllRead']);
        Route::put('/events/{event:slug}/communications/{communication}', [TenantCommunicationController::class, 'update']);
        Route::delete('/events/{event:slug}/communications/{communication}', [TenantCommunicationController::class, 'destroy']);
        Route::post('/events/{event:slug}/communications/{communication}/publish', [TenantCommunicationController::class, 'publish']);
        Route::put('/events/{event:slug}/communications/{communication}/read', [TenantCommunicationController::class, 'markRead']);
        Route::get('/events/{event:slug}/catering', [TenantCateringController::class, 'index']);
        Route::post('/events/{event:slug}/catering/items', [TenantCateringController::class, 'store']);
        Route::put('/events/{event:slug}/catering/items/{menuItem}', [TenantCateringController::class, 'update']);
        Route::delete('/events/{event:slug}/catering/items/{menuItem}', [TenantCateringController::class, 'destroy']);
        Route::get('/events/{event:slug}/access', [TenantAccessController::class, 'index']);
        Route::post('/events/{event:slug}/access/lookup', [TenantAccessController::class, 'lookup']);
        Route::post('/events/{event:slug}/access/check-ins', [TenantAccessController::class, 'store']);
        Route::delete('/events/{event:slug}/access/check-ins/{checkIn}', [TenantAccessController::class, 'destroy']);
        Route::get('/events/{event:slug}/team', [TenantTeamController::class, 'index']);
        Route::post('/events/{event:slug}/team/invitations', [TenantTeamController::class, 'invite']);
        Route::delete('/events/{event:slug}/team/invitations/{invitation}', [TenantTeamController::class, 'cancelInvitation']);
        Route::put('/events/{event:slug}/team/members/{organizationMember}', [TenantTeamController::class, 'updateMember']);
        Route::get('/events/{event:slug}/billing', [TenantBillingController::class, 'index']);
        Route::post('/events/{event:slug}/billing/quotes', [TenantBillingController::class, 'quote']);
        Route::post('/events/{event:slug}/billing/payments', [TenantBillingController::class, 'payment']);
        Route::get('/events/{event:slug}/budget', [TenantBudgetController::class, 'index']);
        Route::post('/events/{event:slug}/budget/categories', [TenantBudgetController::class, 'storeCategory']);
        Route::put('/events/{event:slug}/budget/categories/{category}', [TenantBudgetController::class, 'updateCategory']);
        Route::delete('/events/{event:slug}/budget/categories/{category}', [TenantBudgetController::class, 'destroyCategory']);
        Route::post('/events/{event:slug}/budget/expenses', [TenantBudgetController::class, 'storeExpense']);
        Route::put('/events/{event:slug}/budget/expenses/{expense}', [TenantBudgetController::class, 'updateExpense']);
        Route::put('/events/{event:slug}/budget/expenses/{expense}/approval', [TenantBudgetController::class, 'approveExpense']);
        Route::delete('/events/{event:slug}/budget/expenses/{expense}', [TenantBudgetController::class, 'destroyExpense']);
        Route::get('/events/{event:slug}/inventory', [TenantInventoryController::class, 'index']);
        Route::post('/events/{event:slug}/inventory/items', [TenantInventoryController::class, 'storeItem']);
        Route::put('/events/{event:slug}/inventory/items/{inventoryItem}', [TenantInventoryController::class, 'updateItem']);
        Route::delete('/events/{event:slug}/inventory/items/{inventoryItem}', [TenantInventoryController::class, 'destroyItem']);
        Route::post('/events/{event:slug}/inventory/items/{inventoryItem}/movements', [TenantInventoryController::class, 'storeMovement']);
        Route::post('/events/{event:slug}/inventory/suppliers', [TenantInventoryController::class, 'storeSupplier']);
        Route::post('/events/{event:slug}/inventory/purchase-orders', [TenantInventoryController::class, 'storePurchaseOrder']);
        Route::put('/events/{event:slug}/inventory/purchase-orders/{purchaseOrder}/transition', [TenantInventoryController::class, 'transitionPurchaseOrder']);
        Route::get('/events/{event:slug}/vendors', [TenantVendorController::class, 'index']);
        Route::post('/events/{event:slug}/vendors', [TenantVendorController::class, 'storeVendor']);
        Route::put('/events/{event:slug}/vendors/{vendor}', [TenantVendorController::class, 'updateVendor']);
        Route::delete('/events/{event:slug}/vendors/{vendor}', [TenantVendorController::class, 'destroyVendor']);
        Route::post('/events/{event:slug}/vendor-contracts', [TenantVendorController::class, 'storeContract']);
        Route::put('/events/{event:slug}/vendor-contracts/{vendorContract}/transition', [TenantVendorController::class, 'transitionContract']);
        Route::put('/events/{event:slug}/contract-installments/{contractInstallment}/paid', [TenantVendorController::class, 'markInstallmentPaid']);
        Route::get('/events/{event:slug}/documents', [TenantDocumentController::class, 'index']);
        Route::post('/events/{event:slug}/documents', [TenantDocumentController::class, 'store']);
        Route::post('/events/{event:slug}/documents/{eventDocument}/versions', [TenantDocumentController::class, 'storeVersion']);
        Route::get('/events/{event:slug}/documents/{eventDocument}/versions/{documentVersion}/download', [TenantDocumentController::class, 'download']);
        Route::delete('/events/{event:slug}/documents/{eventDocument}', [TenantDocumentController::class, 'destroy']);
        Route::get('/events/{event:slug}/media', [TenantMediaController::class, 'index']);
        Route::post('/events/{event:slug}/media', [TenantMediaController::class, 'store']);
        Route::post('/events/{event:slug}/media/albums', [TenantMediaController::class, 'storeAlbum']);
        Route::put('/events/{event:slug}/media/{photo}', [TenantMediaController::class, 'update']);
        Route::get('/events/{event:slug}/media/{photo}/content', [TenantMediaController::class, 'content'])->name('tenant-media.content');
        Route::delete('/events/{event:slug}/media/{photo}', [TenantMediaController::class, 'destroy']);
        Route::get('/events/{event:slug}/ticketing', [TenantTicketingController::class, 'index']);
        Route::post('/events/{event:slug}/ticketing/types', [TenantTicketingController::class, 'storeType']);
        Route::post('/events/{event:slug}/ticketing/orders', [TenantTicketingController::class, 'storeOrder']);
        Route::put('/events/{event:slug}/ticketing/orders/{ticketOrder}/confirm', [TenantTicketingController::class, 'confirm']);
        Route::post('/events/{event:slug}/ticketing/scan', [TenantTicketingController::class, 'scan']);
        Route::get('/events/{event:slug}/badges', [TenantBadgeController::class, 'index']);
        Route::post('/events/{event:slug}/badges/templates', [TenantBadgeController::class, 'storeTemplate']);
        Route::put('/events/{event:slug}/badges/templates/{badgeTemplate}', [TenantBadgeController::class, 'updateTemplate']);
        Route::post('/events/{event:slug}/badges/issue', [TenantBadgeController::class, 'issue']);
        Route::put('/events/{event:slug}/badges/{badge}/revoke', [TenantBadgeController::class, 'revoke']);
    });

    Route::get('/entities/{entity}', [EntityController::class, 'index']);
    Route::get('/entities/{entity}/{id}', [EntityController::class, 'show']);
    Route::post('/entities/{entity}', [EntityController::class, 'store']);
    Route::put('/entities/{entity}/{id}', [EntityController::class, 'update']);
    Route::delete('/entities/{entity}/{id}', [EntityController::class, 'destroy']);
    Route::post('/upload', [UploadController::class, 'upload']);
});
